language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - pip install -U pip setuptools
  - pip install -U coveralls pycodestyle pydocstyle pytest-mccabe pytest-random
before_script:
  - pip install -Ur requirements.txt
  - python3 -V
script:
  - coverage run --source=pypo,test -m pytest --random --mccabe
  - pycodestyle --ignore=E501 --statistics --count pypo
  - pydocstyle --ignore=D100,D101,D400,D401 --count pypo
after_success:
  - coveralls
