language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - pip install -U pip setuptools
  - pip install -U coveralls pycodestyle pydocstyle pytest-mccabe pytest-random pylint
before_script:
  - pip install -Ur requirements.txt
  - python3 -V
script:
  - coverage run --source=pypo -m pytest --random --mccabe
  - pycodestyle --ignore=E501 --statistics --count pypo
  - pydocstyle --ignore=D212,D401 --count pypo
  # - pylint pypo
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 && $TRAVIS_OS_NAME == "linux" ]]; then coveralls; fi
