language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -U pip setuptools
  - pip install -U coveralls pycodestyle pydocstyle pytest-mccabe pytest-random
before_script:
  - pip install -Ur requirements.txt
  - python3 -V
script:
  - coverage run --source=pypo,test -m pytest --random --mccabe
  - pycodestyle moler
  - pydocstyle
after_success:
  - coveralls
